In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

In [5]:
df = pd.read_csv('sales.csv')

In [6]:
df

,OrderID,Order Date,Customer_Name,Region,Product,Category,Quantity,Unit Price,Total Amount,Payment Method,Discount,Customer Age,Email,Country,Order Status
0,1001,2024-01-05,John Smith,North,Laptop,Electronics,1,1200,1200,Credit Card,0.0,34,johnsmith@email.com,USA,Completed
1,1002,05/01/2024,Mary Johnson,South,Phone,Electronics,2,800,1600,credit card,5.0,29,mary@email,USA,Completed
2,1003,2024/01/06,Robert Brown,east,Tablet,Electronics,1,400,400,Debit Card,NaN,45,robert@email.com,USA,Completed
3,1004,2024-01-07,Linda Davis,West,Headphones,Electronics,5,50,250,Cash,0.0,abc,linda@email.com,USA,Completed
4,1005,07-01-2024,Michael Wilson,North,Monitor,Electronics,-1,300,-300,Credit Card,10.0,38,michael@email.com,USA,Returned
5,1006,2024-01-08,Sarah Miller,South,Keyboard,Electronics,3,30,90,Credit Card,NaN,27,sarah@email.com,USA,Completed
6,1007,2024-01-08,Sarah Miller,South,Keyboard,Electronics,3,30,90,Credit Card,NaN,27,sarah@email.com,USA,Completed
7,1008,2024-01-09,David Moore,EAST,Mouse,Electronics,10,15,150,Debit Card,0.0,31,david@email.com,USA,Completed
8,1009,2024-01-10,,West,Laptop,Electronics,1,1200,1200,Credit Card,0.0,41,missing@email.com,USA,Completed
9,1010,2024-01-11,James Taylor,North,Phone,Electronics,2,$800,$1600,Credit Card,5.0,36,james@email.com,USA,Completed
10,1011,2024-01-12,Patricia Anderson,South,Tablet,Electronics,1,400,400,Cash,0.0,28,patricia@email.com,USA,Completed
11,1012,2024-01-13,Jennifer Thomas,West,Headphones,Electronics,1000,50,50000,Credit Card,0.0,26,jennifer@email.com,USA,Completed
12,1013,2024-01-14,Charles Jackson,North,Monitor,Electronics,2,NaN,600,Credit Card,0.0,39,charles@email.com,USA,Completed
13,1014,2024-01-15,Barbara White,South,Keyboard,Electronics,3,30,90,Credit Card,0.0,NaN,barbara@email.com,USA,Completed
14,1015,2024-01-16,Christopher Harris,West,Mouse,Electronics,5,15,75,Bitcoin,0.0,33,chris@email.com,USA,Completed
15,1016,2024-01-17,Daniel Martin,North,Laptop,Electronics,1,1200,1200,Credit Card,200.0,42,daniel@email.com,USA,Completed
16,1017,2024-01-18,Nancy Thompson,South,Phone,Electronics,2,800,1600,Debit Card,-5.0,37,nancy@email.com,USA,Completed
17,1018,2024-01-19,Karen Garcia,West,Tablet,Electronics,1,400,400,Credit Card,0.0,29,karen@email.com,USA,cancelled
18,1019,2024-01-20,Steven Martinez,North,Headphones,Electronics,5,50,250,Credit Card,0.0,999,steven@email.com,USA,Completed
19,1020,2024-01-21,Donna Robinson,South,Monitor,Electronics,2,300,600,Cash,0.0,35,donna@email.com,United States,Completed
20,1021,2024-01-22,Paul Clark,West,Keyboard,Electronics,three,30,90,Credit Card,0.0,40,paul@email.com,USA,Completed
21,1022,2024-01-23,Mark Rodriguez,North,Mouse,Electronics,5,15,75,Credit Card,0.0,32,mark@email.com,USA,Completed
22,1023,2024-01-24,Donald Lewis,South,Laptop,Electronics,1,1200,1200,Credit Card,0.0,34,donald@email.com,usa,Completed
23,1024,2024-01-25,George Lee,West,Phone,Electronics,2,800,1600,Credit Card,0.0,36,george@email.com,USA,Completed
24,1025,2024-01-26,Kenneth Walker,North,Tablet,Electronics,1,400,400,Credit Card,0.0,41,kenneth@email.com,USA,Completed
25,1026,2024-01-27,Amy Hall,South,Headphones,Electronics,4,50,200,Credit Card,0.0,25,amy@email.com,USA,Completed
26,1027,2024-01-28,Brian Allen,West,Monitor,Electronics,2,300,600,Debit Card,0.0,44,brian@email.com,USA,Completed
27,1028,2024/01/29,Eric Young,north,Keyboard,Electronics,3,30,90,Credit Card,0.0,38,eric@email.com,USA,Completed
28,1029,29-01-2024,Angela Hernandez,SOUTH,Mouse,Electronics,6,15,90,Cash,0.0,31,angela@email.com,USA,Completed
29,1030,2024-01-30,Jason King,West,Laptop,Electronics,1,1200,1200,Credit Card,0.0,29,jason@email.com,USA,Completed
30,1031,2024-01-31,Susan Wright,North,Phone,Electronics,2,800,1600,Credit Card,0.0,33,susan@email.com,USA,Completed
31,1032,2024-02-01,Frank Lopez,South,Tablet,Electronics,NaN,400,400,Credit Card,0.0,46,frank@email.com,USA,Completed
32,1033,2024-02-02,Margaret Hill,West,Headphones,Electronics,5,50,NaN,Debit Card,0.0,52,margaret@email.com,USA,Completed
33,1034,2024-02-03,,North,Monitor,Electronics,2,300,600,Credit Card,0.0,48,missing2@email.com,USA,Completed
34,1035,2024-02-04,Joshua Scott,South,Keyboard,Electronics,3,thirty,90,Credit Card,0.0,35,josh@email.com,USA,Completed
35,1036,2024-02-05,Andrew Green,West,Mouse,Electronics,5,15,75,Credit Card,0.0,37,andrew@email,USA,Completed
36,1037,2024-02-06,Olivia Adams,North,Laptop,Electronics,1,1200,1200,Credit Card,0.0,22,olivia@email.com,USA,completed
37,1038,2024-02-07,Brandon Baker,South,Phone,Electronics,0,800,0,Credit Card,0.0,39,brandon@email.com,USA,Completed
38,1039,2024-02-08,Justin Nelson,West,Tablet,Electronics,1,400,400,Credit Card,0.0,-5,justin@email.com,USA,Completed
39,1040,2024-02-09,Samantha Carter,North,Headphones,Electronics,3,50,150,Cash,0.0,27,samantha@email.com,USA,Completed
40,1041,2024-02-10,Benjamin Mitchell,South,Monitor,Electronics,2,300,600,Credit Card,0.0,34,ben@email.com,USA,Completed
41,1042,2024-02-11,Evelyn Perez,West,Keyboard,Electronics,3,30,90,Credit Card,0.0,45,evelyn@email.com,USA,Completed
42,1043,2024-02-12,Alexander Roberts,North,Mouse,Electronics,5,15,75,Debit Card,0.0,38,alex@email.com,USA,Completed
43,1044,2024-02-13,Chloe Turner,South,Laptop,Electronics,1,1200,1200,Credit Card,0.0,30,chloe@email.com,USA,Completed
44,1045,2024-02-14,Grace Phillips,West,Phone,Electronics,2,800,1600,Credit Card,0.0,28,grace@email.com,USA,Completed
45,1046,2024-02-15,Jack Campbell,North,Tablet,Electronics,1,400,400,Credit Card,0.0,41,jack@email.com,USA,Completed
46,1047,2024-02-16,Henry Parker,South,Headphones,Electronics,5,50,250,Credit Card,0.0,36,henry@email.com,USA,Completed
47,1048,2024-02-17,Amelia Evans,West,Monitor,Electronics,2,300,600,Credit Card,0.0,33,amelia@email.com,USA,Completed
48,1049,2024-02-18,Logan Edwards,North,Keyboard,Electronics,3,30,90,Credit Card,0.0,47,logan@email.com,USA,Completed
49,1050,2024-02-19,Noah Collins,South,Mouse,Electronics,5,15,75,Credit Card,0.0,26,noah@email.com,USA,Completed

In [7]:
df.head()

,OrderID,Order Date,Customer_Name,Region,Product,Category,Quantity,Unit Price,Total Amount,Payment Method,Discount,Customer Age,Email,Country,Order Status
0,1001,2024-01-05,John Smith,North,Laptop,Electronics,1,1200,1200,Credit Card,0.0,34,johnsmith@email.com,USA,Completed
1,1002,05/01/2024,Mary Johnson,South,Phone,Electronics,2,800,1600,credit card,5.0,29,mary@email,USA,Completed
2,1003,2024/01/06,Robert Brown,east,Tablet,Electronics,1,400,400,Debit Card,NaN,45,robert@email.com,USA,Completed
3,1004,2024-01-07,Linda Davis,West,Headphones,Electronics,5,50,250,Cash,0.0,abc,linda@email.com,USA,Completed
4,1005,07-01-2024,Michael Wilson,North,Monitor,Electronics,-1,300,-300,Credit Card,10.0,38,michael@email.com,USA,Returned

In [8]:
df.columns

Index(['OrderID', 'Order Date', 'Customer_Name', 'Region', 'Product',
       'Category', 'Quantity', 'Unit Price', 'Total Amount', 'Payment Method',
       'Discount', 'Customer Age', 'Email', 'Country', 'Order Status'],
      dtype='str')

In [9]:
df.shape

(50, 15)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OrderID         50 non-null     int64
 1   Order Date      50 non-null     str
 2   Customer_Name   50 non-null     str
 3   Region          50 non-null     str
 4   Product         50 non-null     str
 5   Category        50 non-null     str
 6   Quantity        49 non-null     str
 7   Unit Price      49 non-null     str
 8   Total Amount    49 non-null     str
 9   Payment Method  50 non-null     str
 10  Discount        47 non-null     float64
 11  Customer Age    49 non-null     str
 12  Email           50 non-null     str
 13  Country         50 non-null     str
 14  Order Status    50 non-null     str
dtypes: float64(1), int64(1), str(13)
memory usage: 6.0 KB

In [10]:
df.describe()

          OrderID    Discount
count    50.00000   47.000000
mean   1025.50000    4.574468
std      14.57738   29.188849
min    1001.00000   -5.000000
25%    1013.25000    0.000000
50%    1025.50000    0.000000
75%    1037.75000    0.000000
max    1050.00000  200.000000

In [13]:
df.isna()

,OrderID,Order Date,Customer_Name,Region,Product,Category,Quantity,Unit Price,Total Amount,Payment Method,Discount,Customer Age,Email,Country,Order Status
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [15]:
df.isnull().sum()

OrderID           0
Order Date        0
Customer_Name     0
Region            0
Product           0
Category          0
Quantity          1
Unit Price        1
Total Amount      1
Payment Method    0
Discount          3
Customer Age      1
Email             0
Country           0
Order Status      0
dtype: int64

In [19]:
df.isnull().sum()

OrderID           0
Order Date        0
Customer_Name     0
Region            0
Product           0
Category          0
Quantity          1
Unit Price        1
Total Amount      1
Payment Method    0
Discount          0
Customer Age      1
Email             0
Country           0
Order Status      0
dtype: int64